// Sample seating data for the event
// This can be easily customized for different events
const seatingData = {
    eventName: "Sample Event 2024",
    tables: [
        { number: 1, capacity: 8, x: 0, y: 0 },
        { number: 2, capacity: 8, x: 1, y: 0 },
        { number: 3, capacity: 8, x: 2, y: 0 },
        { number: 4, capacity: 8, x: 3, y: 0 },
        { number: 5, capacity: 10, x: 0, y: 1 },
        { number: 6, capacity: 10, x: 1, y: 1 },
        { number: 7, capacity: 10, x: 2, y: 1 },
        { number: 8, capacity: 10, x: 3, y: 1 },
        { number: 9, capacity: 8, x: 0, y: 2 },
        { number: 10, capacity: 8, x: 1, y: 2 },
        { number: 11, capacity: 8, x: 2, y: 2 },
        { number: 12, capacity: 8, x: 3, y: 2 }
    ],
    guests: [
        { name: "John Smith", table: 1 },
        { name: "Emily Johnson", table: 1 },
        { name: "Michael Brown", table: 1 },
        { name: "Sarah Davis", table: 1 },
        { name: "David Wilson", table: 2 },
        { name: "Lisa Anderson", table: 2 },
        { name: "James Taylor", table: 2 },
        { name: "Jennifer Martinez", table: 2 },
        { name: "Robert Garcia", table: 3 },
        { name: "Maria Rodriguez", table: 3 },
        { name: "William Hernandez", table: 3 },
        { name: "Elizabeth Lopez", table: 3 },
        { name: "Christopher Gonzalez", table: 4 },
        { name: "Jessica Wilson", table: 4 },
        { name: "Daniel Moore", table: 4 },
        { name: "Amanda Thomas", table: 4 },
        { name: "Matthew Jackson", table: 5 },
        { name: "Ashley White", table: 5 },
        { name: "Joshua Harris", table: 5 },
        { name: "Stephanie Martin", table: 5 },
        { name: "Andrew Thompson", table: 6 },
        { name: "Melissa Garcia", table: 6 },
        { name: "Ryan Martinez", table: 6 },
        { name: "Nicole Robinson", table: 6 },
        { name: "Brandon Clark", table: 7 },
        { name: "Samantha Lewis", table: 7 },
        { name: "Kevin Lee", table: 7 },
        { name: "Rachel Walker", table: 7 },
        { name: "Justin Hall", table: 8 },
        { name: "Lauren Allen", table: 8 },
        { name: "Tyler Young", table: 8 },
        { name: "Brittany King", table: 8 },
        { name: "Nathan Wright", table: 9 },
        { name: "Megan Scott", table: 9 },
        { name: "Zachary Green", table: 9 },
        { name: "Hannah Baker", table: 9 },
        { name: "Austin Adams", table: 10 },
        { name: "Victoria Nelson", table: 10 },
        { name: "Kyle Carter", table: 10 },
        { name: "Olivia Mitchell", table: 10 },
        { name: "Dylan Perez", table: 11 },
        { name: "Alexis Roberts", table: 11 },
        { name: "Jordan Turner", table: 11 },
        { name: "Natalie Phillips", table: 11 },
        { name: "Connor Campbell", table: 12 },
        { name: "Grace Parker", table: 12 },
        { name: "Lucas Evans", table: 12 },
        { name: "Sophia Edwards", table: 12 }
    ]
};
